version: "3"

services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_USER=gettingstarted"
      - "POSTGRES_DB=gettingstarted"
      - "POSTGRES_PASSWORD=gettingstarted"
    expose:
      - "5432"
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis