apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nkobani.fullname" . }}
  labels:
    {{- include "nkobani.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nkobani.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nkobani.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nkobani.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: redis-url
                  name: {{ include "nkobani.fullname" . }}
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-url
                  name: {{ include "nkobani.fullname" . }}
            - name: RABBITMQ_QUEUE_NAME
              value: {{ .Values.rabbitmq.queueName }}

            - name: KEYCLOAK_URL
              value: {{ .Values.keycloak.url }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.keycloak.realm }}
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: keycloak-client-id
                  name: {{ include "nkobani.fullname" . }}
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: keycloak-client-secret
                  name: {{ include "nkobani.fullname" . }}
            - name: HASURA_GRAPHQL_ENDPOINT
              value: {{ .Values.hasura.url }}
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  key: hasura-admin-secret
                  name: {{ include "nkobani.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
